[project]
name = "mcp-vms"
version = "0.1.0"
description = "VMS Video Fetch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.2.1",
    "numpy>=2.2.4",
    "pillow>=11.1.0",
]
